import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PlayCircleOutlined } from '@ant-design/icons';
import { Button, Card, Form, Input, Space, Table, Tabs, Tag, message } from 'antd';
import { changePassword, getAuditLogs, getSyncTasks, runSyncTask, updateProfile } from '../../services/admin';
import type { AuditLog, SyncTask } from '../../types/admin';
import { useAuthStore } from '../../store/auth';

/** 集中管理当前账号、同步任务和后台审计日志。 */
export function SystemPage() {
  const client = useQueryClient(); const [messageApi, holder] = message.useMessage(); const user = useAuthStore((state) => state.user); const setUser = useAuthStore((state) => state.setUser); const clearSession = useAuthStore((state) => state.clearSession); const [profileForm] = Form.useForm(); const [passwordForm] = Form.useForm();
  const { data: tasks = [], isLoading: tasksLoading } = useQuery({ queryKey: ['sync-tasks'], queryFn: getSyncTasks }); const { data: logs = [], isLoading: logsLoading } = useQuery({ queryKey: ['audit-logs'], queryFn: getAuditLogs });
  // 账号资料、密码和同步任务分别维护独立提交状态，避免操作相互阻塞。
  const profileMutation = useMutation({ mutationFn: (values: { displayName: string }) => updateProfile(values.displayName), onSuccess: (updated) => { setUser(updated); messageApi.success('显示名称已更新'); }, onError: () => messageApi.error('资料更新失败') });
  const passwordMutation = useMutation({ mutationFn: (values: { currentPassword: string; newPassword: string }) => changePassword(values.currentPassword, values.newPassword), onSuccess: () => { messageApi.success('密码已修改，请重新登录'); clearSession(); }, onError: () => messageApi.error('密码修改失败，请检查当前密码') });
  const runMutation = useMutation({ mutationFn: runSyncTask, onSuccess: () => { messageApi.success('模拟同步任务执行成功'); void client.invalidateQueries({ queryKey: ['sync-tasks'] }); void client.invalidateQueries({ queryKey: ['audit-logs'] }); }, onError: () => messageApi.error('任务执行失败') });
  const statusLabels = { PENDING: ['待执行', 'default'], RUNNING: ['执行中', 'processing'], SUCCESS: ['成功', 'green'], FAILED: ['失败', 'red'] } as const;
  // 三个标签页内容单独声明，便于主 JSX 清晰表达页面结构。
  const account = <div className="settings-grid"><Card title="账号资料" className="module-card"><Form form={profileForm} layout="vertical" initialValues={{ displayName: user?.displayName }} onFinish={(values) => profileMutation.mutate(values)}><Form.Item label="登录账号"><Input value={user?.username} disabled /></Form.Item><Form.Item label="显示名称" name="displayName" rules={[{ required: true }, { max: 50 }]}><Input /></Form.Item><Button type="primary" htmlType="submit" loading={profileMutation.isPending}>保存资料</Button></Form></Card><Card title="修改密码" className="module-card"><Form form={passwordForm} layout="vertical" onFinish={(values) => passwordMutation.mutate(values)}><Form.Item label="当前密码" name="currentPassword" rules={[{ required: true }]}><Input.Password /></Form.Item><Form.Item label="新密码" name="newPassword" rules={[{ required: true }, { min: 8, message: '密码至少 8 位' }]}><Input.Password /></Form.Item><Form.Item label="确认新密码" name="confirmPassword" dependencies={['newPassword']} rules={[{ required: true }, ({ getFieldValue }) => ({ validator(_, value) { return !value || getFieldValue('newPassword') === value ? Promise.resolve() : Promise.reject(new Error('两次输入的密码不一致')); } })]}><Input.Password /></Form.Item><Button type="primary" htmlType="submit" loading={passwordMutation.isPending}>修改密码</Button></Form></Card></div>;
  const taskTable = <Card className="module-card"><Table rowKey="id" loading={tasksLoading} dataSource={tasks} columns={[{ title: '任务名称', dataIndex: 'name', render: (value) => <strong>{value}</strong> }, { title: '任务类型', dataIndex: 'type' }, { title: '状态', dataIndex: 'status', render: (value: keyof typeof statusLabels) => <Tag color={statusLabels[value][1]}>{statusLabels[value][0]}</Tag> }, { title: '执行次数', dataIndex: 'runCount' }, { title: '最近执行', dataIndex: 'lastRunAt', render: (value) => value ? new Date(value).toLocaleString('zh-CN') : '-' }, { title: '操作', render: (_, item: SyncTask) => <Button type="primary" ghost icon={<PlayCircleOutlined />} loading={runMutation.isPending && runMutation.variables === item.id} onClick={() => runMutation.mutate(item.id)}>立即执行</Button> }]} /></Card>;
  const logTable = <Card className="module-card"><Table rowKey="id" loading={logsLoading} dataSource={logs} pagination={{ pageSize: 15 }} columns={[{ title: '时间', dataIndex: 'createdAt', width: 180, render: (value) => new Date(value).toLocaleString('zh-CN') }, { title: '模块', dataIndex: 'module', width: 120 }, { title: '动作', dataIndex: 'action', width: 100 }, { title: '变更内容', dataIndex: 'summary' }, { title: '管理员', dataIndex: 'admin', width: 120, render: (value: AuditLog['admin']) => value?.displayName || '系统' }]} /></Card>;
  return <>{holder}<Tabs defaultActiveKey="account" items={[{ key: 'account', label: '账号设置', children: account }, { key: 'tasks', label: '同步任务', children: taskTable }, { key: 'logs', label: '操作日志', children: logTable }]} /></>;
}
