import { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowLeftOutlined, PlusOutlined, SaveOutlined } from '@ant-design/icons';
import { Background, Controls, ReactFlow, addEdge, useEdgesState, useNodesState } from '@xyflow/react';
import type { Connection, Edge, Node } from '@xyflow/react';
import { Button, Card, Drawer, Form, Input, Select, Space, Spin, Typography, message } from 'antd';
import { useNavigate, useParams } from 'react-router-dom';
import { getChain, getCompanyOptions, saveChainGraph } from '../../services/admin';

interface ChainNodeData extends Record<string, unknown> { label: string; type: string; stage: string; description?: string | null; companyIds: number[] }
type FlowNode = Node<ChainNodeData>;

/** 基于 React Flow 编辑产业链节点、公司归属和上下游连线。 */
export function ChainEditorPage() {
  const { id } = useParams(); const chainId = Number(id); const navigate = useNavigate(); const [messageApi, holder] = message.useMessage(); const [form] = Form.useForm();
  const { data: chain, isLoading } = useQuery({ queryKey: ['chain', chainId], queryFn: () => getChain(chainId) });
  const { data: companies = [] } = useQuery({ queryKey: ['company-options'], queryFn: getCompanyOptions });
  const [nodes, setNodes, onNodesChange] = useNodesState<FlowNode>([]); const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]); const [editingId, setEditingId] = useState<string | null>(null);
  useEffect(() => { if (!chain) return; setNodes(chain.nodes.map((node) => ({ id: String(node.id), position: { x: node.positionX, y: node.positionY }, data: { label: node.name, type: node.type, stage: node.stage, description: node.description, companyIds: node.companyIds }, className: `chain-node chain-node-${node.stage}` }))); setEdges(chain.edges.map((edge) => ({ id: String(edge.id), source: String(edge.sourceNodeId), target: String(edge.targetNodeId), label: edge.label || undefined, animated: true }))); }, [chain, setEdges, setNodes]);
  // 保存前把 React Flow 的节点/连线转换为后端图谱 DTO。
  const saveMutation = useMutation({ mutationFn: () => saveChainGraph(chainId, { nodes: nodes.map((node) => ({ clientId: node.id, name: node.data.label, type: node.data.type, stage: node.data.stage, description: node.data.description || null, positionX: node.position.x, positionY: node.position.y, companyIds: node.data.companyIds })), edges: edges.map((edge) => ({ source: edge.source, target: edge.target, label: typeof edge.label === 'string' ? edge.label : null })) }), onSuccess: () => messageApi.success('产业链图谱已保存'), onError: () => messageApi.error('图谱保存失败') });
  /** 在画布上创建一个带默认位置和属性的新节点。 */
  const addNode = () => { const id = `new-${Date.now()}`; const node: FlowNode = { id, position: { x: 180 + nodes.length * 35, y: 120 + nodes.length * 30 }, data: { label: '新节点', type: 'stage', stage: 'midstream', companyIds: [] }, className: 'chain-node chain-node-midstream' }; setNodes((items) => [...items, node]); openNode(node); };
  /** 选中节点并把节点数据回填到属性表单。 */
  const openNode = (node: FlowNode) => { setEditingId(node.id); form.setFieldsValue({ name: node.data.label, type: node.data.type, stage: node.data.stage, description: node.data.description, companyIds: node.data.companyIds }); };
  /** 把属性表单修改合并回当前节点。 */
  const updateNode = (values: { name: string; type: string; stage: string; description?: string; companyIds: number[] }) => { setNodes((items) => items.map((node) => node.id === editingId ? { ...node, data: { label: values.name, type: values.type, stage: values.stage, description: values.description, companyIds: values.companyIds || [] }, className: `chain-node chain-node-${values.stage}` } : node)); setEditingId(null); };
  if (isLoading || !chain) return <div className="page-loading"><Spin size="large" /></div>;
  return <>{holder}<Card className="module-card chain-editor-card" title={<Space><Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/chains')}>返回</Button><div><Typography.Text strong>{chain.name}</Typography.Text><Typography.Text type="secondary" className="chain-editor-subtitle">拖拽节点并建立上下游连线</Typography.Text></div></Space>} extra={<Space><Button icon={<PlusOutlined />} onClick={addNode}>添加节点</Button><Button type="primary" icon={<SaveOutlined />} loading={saveMutation.isPending} onClick={() => saveMutation.mutate()}>保存图谱</Button></Space>}><div className="chain-canvas"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={(connection: Connection) => setEdges((items) => addEdge({ ...connection, animated: true }, items))} onNodeDoubleClick={(_, node) => openNode(node)} fitView deleteKeyCode="Delete"><Background /><Controls /></ReactFlow></div></Card><Drawer title="节点属性" open={Boolean(editingId)} onClose={() => setEditingId(null)} width={420} extra={<Button type="primary" onClick={() => form.submit()}>应用</Button>}><Form form={form} layout="vertical" onFinish={updateNode}><Form.Item label="节点名称" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="节点类型" name="type"><Select options={[{ value: 'stage', label: '产业环节' }, { value: 'product', label: '产品' }, { value: 'material', label: '原材料' }, { value: 'company', label: '公司' }]} /></Form.Item><Form.Item label="产业位置" name="stage"><Select options={[{ value: 'upstream', label: '上游' }, { value: 'midstream', label: '中游' }, { value: 'downstream', label: '下游' }]} /></Form.Item><Form.Item label="关联公司" name="companyIds"><Select mode="multiple" showSearch optionFilterProp="label" options={companies.map((company) => ({ value: company.id, label: `${company.stockCode} ${company.shortName || company.name}` }))} /></Form.Item><Form.Item label="说明" name="description"><Input.TextArea rows={4} /></Form.Item><Button danger block onClick={() => { setNodes((items) => items.filter((node) => node.id !== editingId)); setEdges((items) => items.filter((edge) => edge.source !== editingId && edge.target !== editingId)); setEditingId(null); }}>删除节点</Button></Form></Drawer></>;
}
