import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckOutlined, CloseOutlined, EyeOutlined } from '@ant-design/icons';
import { Button, Card, Drawer, Form, Input, Select, Space, Table, Tag, Typography, message } from 'antd';
import { getAiResults, reviewAiResult } from '../../services/admin';
import type { AiContent, AiResult } from '../../types/admin';

export function AiReviewPage() {
  const client = useQueryClient(); const [messageApi, holder] = message.useMessage(); const [status, setStatus] = useState<string>(); const [selected, setSelected] = useState<AiResult | null>(null); const [form] = Form.useForm();
  const { data = [], isLoading } = useQuery({ queryKey: ['ai-results', status], queryFn: () => getAiResults(status) });
  useEffect(() => { if (!selected) return; const result = selected.editedResult || selected.rawResult; form.setFieldsValue({ ...result, products: result.products?.join('\n'), suggestedTags: result.suggestedTags?.join('\n'), risks: result.risks?.join('\n'), opportunities: result.opportunities?.join('\n') }); }, [form, selected]);
  const mutation = useMutation({ mutationFn: ({ reviewStatus, values }: { reviewStatus: 'APPROVED' | 'REJECTED'; values: Record<string, string> }) => { const lines = (value?: string) => value?.split('\n').map((item) => item.trim()).filter(Boolean); const result: AiContent = { summary: values.summary, industryImpact: values.industryImpact, products: lines(values.products), suggestedTags: lines(values.suggestedTags), risks: lines(values.risks), opportunities: lines(values.opportunities) }; return reviewAiResult(selected!.id, reviewStatus, result); }, onSuccess: () => { messageApi.success('审核结果已保存'); setSelected(null); void client.invalidateQueries({ queryKey: ['ai-results'] }); void client.invalidateQueries({ queryKey: ['announcements'] }); }, onError: () => messageApi.error('审核失败') });
  const labels = { PENDING: ['待审核', 'gold'], APPROVED: ['已通过', 'green'], REJECTED: ['已驳回', 'red'] } as const;
  const submit = (reviewStatus: 'APPROVED' | 'REJECTED') => form.validateFields().then((values) => mutation.mutate({ reviewStatus, values }));
  return <>{holder}<Card className="module-card" title="AI 解析审核"><Select allowClear value={status} onChange={setStatus} placeholder="审核状态" className="module-filter" options={Object.entries(labels).map(([value, item]) => ({ value, label: item[0] }))} /><Table rowKey="id" loading={isLoading} dataSource={data} scroll={{ x: 920 }} columns={[
    { title: '公告', dataIndex: 'announcement', width: 340, ellipsis: true, render: (value: AiResult['announcement']) => <div className="company-name"><strong>{value.title}</strong><span>{value.company.shortName || value.company.name}</span></div> }, { title: '模型', dataIndex: 'modelName', width: 140 }, { title: '状态', dataIndex: 'status', width: 100, render: (value: keyof typeof labels) => <Tag color={labels[value][1]}>{labels[value][0]}</Tag> }, { title: '审核人', dataIndex: 'reviewer', width: 100, render: (value: AiResult['reviewer']) => value?.displayName || '-' }, { title: '更新时间', dataIndex: 'reviewedAt', width: 170, render: (value) => value ? new Date(value).toLocaleString('zh-CN') : '-' }, { title: '操作', width: 110, render: (_, item: AiResult) => <Button type="text" icon={<EyeOutlined />} onClick={() => setSelected(item)}>审核详情</Button> },
  ]} /></Card><Drawer title="AI 解析审核" open={Boolean(selected)} width={760} onClose={() => setSelected(null)} extra={<Space><Button danger icon={<CloseOutlined />} loading={mutation.isPending} onClick={() => submit('REJECTED')}>驳回</Button><Button type="primary" icon={<CheckOutlined />} loading={mutation.isPending} onClick={() => submit('APPROVED')}>通过</Button></Space>} destroyOnHidden><Typography.Title level={5}>公告原文</Typography.Title><Card size="small" className="review-source"><Typography.Text strong>{selected?.announcement.title}</Typography.Text><Typography.Paragraph>{selected?.announcement.content || '暂无公告正文'}</Typography.Paragraph></Card><Typography.Title level={5}>解析结果（可修订）</Typography.Title><Form form={form} layout="vertical"><Form.Item label="摘要" name="summary" rules={[{ required: true }]}><Input.TextArea rows={4} /></Form.Item><Form.Item label="产业影响" name="industryImpact"><Input.TextArea rows={3} /></Form.Item><div className="form-grid"><Form.Item label="提取产品（每行一项）" name="products"><Input.TextArea rows={5} /></Form.Item><Form.Item label="建议标签（每行一项）" name="suggestedTags"><Input.TextArea rows={5} /></Form.Item></div><div className="form-grid"><Form.Item label="风险（每行一项）" name="risks"><Input.TextArea rows={5} /></Form.Item><Form.Item label="机会（每行一项）" name="opportunities"><Input.TextArea rows={5} /></Form.Item></div></Form></Drawer></>;
}
