import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { DeleteOutlined, EditOutlined, PlusOutlined, RobotOutlined } from '@ant-design/icons';
import { Button, Card, Drawer, Form, Input, Popconfirm, Select, Space, Table, Tag, message } from 'antd';
import { deleteAnnouncement, getAnnouncements, getCompanyOptions, parseAnnouncement, saveAnnouncement } from '../../services/admin';
import type { Announcement } from '../../types/admin';

// 后端状态值到中文文案和 Ant Design 颜色的映射。
const parseLabels = { PENDING: ['待解析', 'default'], RUNNING: ['解析中', 'processing'], SUCCESS: ['已解析', 'cyan'], FAILED: ['失败', 'red'] } as const;
const reviewLabels = { PENDING: ['待审核', 'gold'], APPROVED: ['已通过', 'green'], REJECTED: ['已驳回', 'red'] } as const;

/** 公告文档列表，负责筛选、编辑、删除和触发 AI 解析。 */
export function AnnouncementPage() {
  const client = useQueryClient(); const [messageApi, holder] = message.useMessage(); const [form] = Form.useForm(); const [page, setPage] = useState(1); const [companyId, setCompanyId] = useState<number>(); const [keyword, setKeyword] = useState(''); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Announcement | null>(null);
  const { data, isLoading } = useQuery({ queryKey: ['announcements', page, companyId, keyword], queryFn: () => getAnnouncements({ page, pageSize: 10, companyId, keyword: keyword || undefined }) });
  const { data: companies = [] } = useQuery({ queryKey: ['company-options'], queryFn: getCompanyOptions }); const refresh = () => void client.invalidateQueries({ queryKey: ['announcements'] });
  // 将宽松的表单值显式转换成公告接口需要的字段类型。
  const saveMutation = useMutation({ mutationFn: (values: Record<string, unknown>) => saveAnnouncement(editing?.id ?? null, { companyId: Number(values.companyId), title: String(values.title), sourceUrl: String(values.sourceUrl || '') || null, sourceName: String(values.sourceName || '') || null, category: String(values.category || '') || null, content: String(values.content || '') || null, publishedAt: String(values.publishedAt) }), onSuccess: () => { messageApi.success('公告已保存'); setOpen(false); refresh(); }, onError: () => messageApi.error('公告保存失败') });
  const parseMutation = useMutation({ mutationFn: parseAnnouncement, onSuccess: () => { messageApi.success('模拟 AI 解析已完成'); refresh(); void client.invalidateQueries({ queryKey: ['ai-results'] }); }, onError: () => messageApi.error('解析失败') });
  const deleteMutation = useMutation({ mutationFn: deleteAnnouncement, onSuccess: () => { messageApi.success('公告已删除'); refresh(); }, onError: () => messageApi.error('删除失败') });
  /** 打开公告表单，并把 ISO 时间转换成日期输入框格式。 */
  const edit = (item?: Announcement) => { setEditing(item ?? null); form.setFieldsValue(item ? { ...item, publishedAt: item.publishedAt.slice(0, 10) } : { publishedAt: new Date().toISOString().slice(0, 10) }); setOpen(true); };
  return <>{holder}<Card className="module-card" title="公告文档" extra={<Button type="primary" icon={<PlusOutlined />} onClick={() => edit()}>新增公告</Button>}><Space wrap className="module-toolbar"><Input.Search value={keyword} onChange={(event) => setKeyword(event.target.value)} onSearch={() => setPage(1)} placeholder="搜索公告标题" style={{ width: 260 }} /><Select allowClear showSearch optionFilterProp="label" value={companyId} onChange={(value) => { setCompanyId(value); setPage(1); }} placeholder="筛选公司" style={{ width: 220 }} options={companies.map((item) => ({ value: item.id, label: `${item.stockCode} ${item.shortName || item.name}` }))} /></Space><Table rowKey="id" loading={isLoading} dataSource={data?.items} pagination={{ current: page, total: data?.pagination.total, pageSize: 10, onChange: setPage }} scroll={{ x: 1100 }} columns={[
    { title: '公告标题', dataIndex: 'title', width: 320, ellipsis: true, render: (value) => <strong>{value}</strong> }, { title: '公司', dataIndex: 'company', width: 150, render: (value: Announcement['company']) => value.shortName || value.name }, { title: '类型', dataIndex: 'category', width: 110, render: (value) => value || '-' }, { title: '发布日期', dataIndex: 'publishedAt', width: 120, render: (value) => value.slice(0, 10) }, { title: '解析', dataIndex: 'parseStatus', width: 90, render: (value: keyof typeof parseLabels) => <Tag color={parseLabels[value][1]}>{parseLabels[value][0]}</Tag> }, { title: '审核', dataIndex: 'reviewStatus', width: 90, render: (value: keyof typeof reviewLabels) => <Tag color={reviewLabels[value][1]}>{reviewLabels[value][0]}</Tag> }, { title: '操作', width: 260, fixed: 'right', render: (_, item: Announcement) => <Space><Button type="text" icon={<RobotOutlined />} loading={parseMutation.isPending && parseMutation.variables === item.id} onClick={() => parseMutation.mutate(item.id)}>AI 解析</Button><Button type="text" icon={<EditOutlined />} onClick={() => edit(item)}>编辑</Button><Popconfirm title="确认删除公告？" onConfirm={() => deleteMutation.mutate(item.id)}><Button type="text" danger icon={<DeleteOutlined />}>删除</Button></Popconfirm></Space> },
  ]} /></Card><Drawer title={editing ? '编辑公告' : '新增公告'} open={open} width={620} onClose={() => setOpen(false)} extra={<Button type="primary" loading={saveMutation.isPending} onClick={() => form.submit()}>保存</Button>} destroyOnHidden><Form form={form} layout="vertical" onFinish={(values) => saveMutation.mutate(values)}><Form.Item label="所属公司" name="companyId" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={companies.map((item) => ({ value: item.id, label: `${item.stockCode} ${item.shortName || item.name}` }))} /></Form.Item><Form.Item label="公告标题" name="title" rules={[{ required: true }]}><Input /></Form.Item><div className="form-grid"><Form.Item label="公告类型" name="category"><Input /></Form.Item><Form.Item label="发布日期" name="publishedAt" rules={[{ required: true }]}><Input type="date" /></Form.Item></div><div className="form-grid"><Form.Item label="来源名称" name="sourceName"><Input /></Form.Item><Form.Item label="原文地址" name="sourceUrl" rules={[{ type: 'url' }]}><Input /></Form.Item></div><Form.Item label="公告正文" name="content"><Input.TextArea rows={12} /></Form.Item></Form></Drawer></>;
}
