import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { DeleteOutlined, EditOutlined, MinusCircleOutlined, PlusOutlined } from '@ant-design/icons';
import { Button, Card, Drawer, Form, Input, InputNumber, Popconfirm, Select, Space, Table, Tag, message } from 'antd';
import { deleteQuiz, getChains, getCompanyOptions, getQuizzes, saveQuiz } from '../../services/admin';
import type { Quiz } from '../../types/admin';

const typeLabels: Record<string, string> = { single: '单选题', multiple: '多选题', judge: '判断题', guess_company: '猜公司', chain_node: '产业链节点题' };
const difficultyLabels: Record<string, string> = { easy: '简单', medium: '中等', hard: '困难' };

/** 题库列表与题目新增、编辑、删除页面。 */
export function QuizPage() {
  const client = useQueryClient(); const [messageApi, holder] = message.useMessage(); const [form] = Form.useForm(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Quiz | null>(null); const [filters, setFilters] = useState<Record<string, unknown>>({});
  const { data = [], isLoading } = useQuery({ queryKey: ['quizzes', filters], queryFn: () => getQuizzes(filters) }); const { data: companies = [] } = useQuery({ queryKey: ['company-options'], queryFn: getCompanyOptions }); const { data: chains = [] } = useQuery({ queryKey: ['chains'], queryFn: getChains });
  /** 刷新题库列表缓存。 */
  const refresh = () => void client.invalidateQueries({ queryKey: ['quizzes'] });
  // 将表单值转换为题目接口的明确类型，空关联编号统一提交 null。
  const saveMutation = useMutation({ mutationFn: (values: Record<string, unknown>) => saveQuiz(editing?.id ?? null, { type: String(values.type), question: String(values.question), options: values.options as string[] || null, answer: String(values.answer), explanation: String(values.explanation || '') || null, difficulty: String(values.difficulty), score: Number(values.score), companyId: Number(values.companyId) || null, chainId: Number(values.chainId) || null, status: String(values.status) }), onSuccess: () => { messageApi.success('题目已保存'); setOpen(false); refresh(); }, onError: () => messageApi.error('题目保存失败') });
  const deleteMutation = useMutation({ mutationFn: deleteQuiz, onSuccess: () => { messageApi.success('题目已删除'); refresh(); }, onError: () => messageApi.error('删除失败') });
  /** 打开新增或编辑题目弹窗，并设置合理的默认选项。 */
  const edit = (item?: Quiz) => { setEditing(item ?? null); form.setFieldsValue(item ? { ...item, options: item.options || [] } : { type: 'single', difficulty: 'medium', score: 10, status: 'DRAFT', options: ['', '', '', ''] }); setOpen(true); };
  return <>{holder}<Card className="module-card" title="题库管理" extra={<Button type="primary" icon={<PlusOutlined />} onClick={() => edit()}>新增题目</Button>}><Space wrap className="module-toolbar"><Select allowClear placeholder="题型" style={{ width: 150 }} onChange={(type) => setFilters((value) => ({ ...value, type }))} options={Object.entries(typeLabels).map(([value, label]) => ({ value, label }))} /><Select allowClear placeholder="难度" style={{ width: 120 }} onChange={(difficulty) => setFilters((value) => ({ ...value, difficulty }))} options={Object.entries(difficultyLabels).map(([value, label]) => ({ value, label }))} /><Select allowClear placeholder="状态" style={{ width: 120 }} onChange={(status) => setFilters((value) => ({ ...value, status }))} options={[{ value: 'DRAFT', label: '草稿' }, { value: 'PUBLISHED', label: '已发布' }, { value: 'ARCHIVED', label: '已归档' }]} /></Space><Table rowKey="id" loading={isLoading} dataSource={data} scroll={{ x: 1000 }} columns={[
    { title: '题目', dataIndex: 'question', width: 420, ellipsis: true, render: (value) => <strong>{value}</strong> }, { title: '题型', dataIndex: 'type', width: 120, render: (value) => typeLabels[value] || value }, { title: '难度', dataIndex: 'difficulty', width: 90, render: (value) => difficultyLabels[value] || value }, { title: '分值', dataIndex: 'score', width: 80 }, { title: '关联内容', width: 150, render: (_, item: Quiz) => item.company?.shortName || item.company?.name || item.chain?.name || '-' }, { title: '状态', dataIndex: 'status', width: 90, render: (value) => <Tag color={value === 'PUBLISHED' ? 'cyan' : 'default'}>{value === 'PUBLISHED' ? '已发布' : value === 'DRAFT' ? '草稿' : '已归档'}</Tag> }, { title: '操作', width: 170, render: (_, item: Quiz) => <Space><Button type="text" icon={<EditOutlined />} onClick={() => edit(item)}>编辑</Button><Popconfirm title="确认删除题目？" onConfirm={() => deleteMutation.mutate(item.id)}><Button type="text" danger icon={<DeleteOutlined />}>删除</Button></Popconfirm></Space> },
  ]} /></Card><Drawer title={editing ? '编辑题目' : '新增题目'} open={open} onClose={() => setOpen(false)} width={680} extra={<Button type="primary" loading={saveMutation.isPending} onClick={() => form.submit()}>保存</Button>} destroyOnHidden><Form form={form} layout="vertical" onFinish={(values) => saveMutation.mutate(values)}><div className="form-grid"><Form.Item label="题型" name="type" rules={[{ required: true }]}><Select options={Object.entries(typeLabels).map(([value, label]) => ({ value, label }))} /></Form.Item><Form.Item label="难度" name="difficulty"><Select options={Object.entries(difficultyLabels).map(([value, label]) => ({ value, label }))} /></Form.Item></div><Form.Item label="题目" name="question" rules={[{ required: true }]}><Input.TextArea rows={4} /></Form.Item><Form.List name="options">{(fields, { add, remove }) => <><label className="form-list-label">选项</label>{fields.map((field, index) => <Space key={field.key} className="option-row"><Form.Item {...field} rules={[{ required: true, message: '请输入选项' }]}><Input placeholder={`选项 ${index + 1}`} /></Form.Item><Button type="text" danger icon={<MinusCircleOutlined />} onClick={() => remove(field.name)} /></Space>)}<Button block icon={<PlusOutlined />} onClick={() => add('')}>添加选项</Button></>}</Form.List><Form.Item label="正确答案" name="answer" rules={[{ required: true }]}><Input placeholder="多选答案使用英文逗号分隔" /></Form.Item><Form.Item label="答案解析" name="explanation"><Input.TextArea rows={4} /></Form.Item><div className="form-grid"><Form.Item label="关联公司" name="companyId"><Select allowClear showSearch optionFilterProp="label" options={companies.map((item) => ({ value: item.id, label: `${item.stockCode} ${item.shortName || item.name}` }))} /></Form.Item><Form.Item label="关联产业链" name="chainId"><Select allowClear options={chains.map((item) => ({ value: item.id, label: item.name }))} /></Form.Item></div><div className="form-grid"><Form.Item label="分值" name="score"><InputNumber min={1} max={100} style={{ width: '100%' }} /></Form.Item><Form.Item label="发布状态" name="status"><Select options={[{ value: 'DRAFT', label: '草稿' }, { value: 'PUBLISHED', label: '已发布' }, { value: 'ARCHIVED', label: '已归档' }]} /></Form.Item></div></Form></Drawer></>;
}
